name: Build Windows

on:
  push:
    branches:
      - '*'           # Runs on all branch pushes
  pull_request:       # Runs on all pull requests to any branch

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get env
        run: |
          ls env:

      - name: Get version from package.json
        id: get_version
        run: |
          $version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
          echo "version=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Get env
        run: |
          ls env:

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Adjust this to the required Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the build command
      - name: Build for Windows
        run: npm run build:win

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Upload Release Assets
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v1
        with:
          files: 'admin-goowee-finale-${{ env.version }}-setup.exe'

      # Upload the entire output directory as an artifact
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "build-windows-output"
          path: dist/admin-goowee-finale-${{ env.version }}-setup.exe  # Replace with the actual output directory
          retention-days: 7   # Adjust retention period as needed GITHUB_RUN_ID
