name: Build Windows

permissions:
  contents: write

on:
  push:
    branches:
      - '*'           # Runs on all branch pushes

jobs:
  cross-platform-task:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Run the script on Linux
      - name: Run Python Script on Linux
        run: |
          cd tools/lookup_table/
          python3 generate_lookup_table.py --logging debug

      # Step 3: Upload the output as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lookup-output
          path: tools/lookup_table/output/lookuptable.json

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: |
          $version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
          echo "version=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      # - name: Generate character lookup table
      #   id: gen_char_lookup
      #   run: |
      #     ls
      #     cd tools\lookup_table
      #     ls
      #     rm output\lookuptable.json
      #     python3 ./generate_lookup_table.py --logging debug
      #     cat output\lookuptable.json

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: lookup-output
          path: tools/lookup_table/output/lookuptable.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Adjust this to the required Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build for Windows
        run: npm run build:win

      - name: Get env
        run: |
          ls env:

      - name: Rename exe
        run: |
          $NewSetupName = "Admin-GooWee-Setup-${{ github.ref_name }}-${{ github.run_number }}.exe"
          echo "newsetupname=$NewSetupName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          Rename-Item -Path "dist/admin-goowee-finale-${{ env.version }}-setup.exe" -NewName "$NewSetupName"
      
      - name: Get env
        run: |
          ls env:

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "build-windows-output"
          path: dist/${{ env.newsetupname }}
          retention-days: 7
