name: Check merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  cross-platform-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Python Script on Linux
        run: |
          cd tools/lookup_table/
          python3 generate_lookup_table.py --logging debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lookup-output
          path: tools/lookup_table/output/lookuptable.json

  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set version in src/renderer/src/assets/version.json
        id: set_version
        run: |
          # for getting the correct filename to rename
          $envversion = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
          echo "envversion=$envversion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

          # for populating src/renderer/src/assets/version.json
          $version = "${{ github.run_number }}"
          $branch = "${{ github.ref_name }}"
          $commit_hash = "${{github.sha }}"

          $version_data = @{
            "version"     = $version
            "branch"      = $branch
            "commit hash" = $commit_hash
          }

          $version_data | ConvertTo-Json | set-content -Force -Path src/renderer/src/assets/version.json

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: lookup-output
          path: tools\lookup_table\output\

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build for Windows
        run: npm run build:win

      - name: Get debug info
        run: |
          ls dist
          # ls dist/${{ env.newsetupname }}
          cat latest.yml