name: Build and Release Windows

on:
  push:
    tags:
      - '*'           # This triggers the workflow on any tag push

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Adjust this to your required Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the build command
      - name: Build for Windows
        run: npm run build:win

      # Step 5: Create a release and upload the output as release assets
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: path/to/output-directory/*   # Replace with the path to your output directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
